<Project>

  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <EpimeteoVersion>0.1.0</EpimeteoVersion>
    <Version>$(EpimeteoVersion)</Version>
  </PropertyGroup>

</Project>
